os:
  - linux
language: cpp
sudo: false
before_install:
  - export CC=arm-none-eabi-gcc
  - export CXX=arm-none-eabi-g++
  - export DEVKITPRO=${HOME}/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export PORTLIBS=${DEVKITPRO}/portlibs/armv6k
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - perl devkitARMupdate.pl
  - sh .travis-deps.sh
  
script:
- make clean
- make
